"""
tools/profile_store.py

Mock candidate profile store simulating a talent database.
In production this would be backed by a real ATS, LinkedIn MCP, or database.

Contains 20 diverse profiles varying in seniority, tech stack, location,
availability, and compensation expectations to produce meaningful score spreads.
"""

from typing import Optional

CANDIDATE_PROFILES: list[dict] = [
    {
        "id": "c001",
        "name": "Arjun Mehta",
        "current_title": "Senior Backend Engineer",
        "years_experience": 6,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "Kubernetes", "AWS", "Kafka", "microservices"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "28-32 LPA",
        "education": "B.Tech Computer Science, BITS Pilani",
        "recent_companies": ["Razorpay", "Flipkart"],
        "availability": "immediate",
        "bio": "Fintech-focused backend engineer with deep payments domain experience. Built and scaled payment processing systems handling 10M+ transactions/day at Razorpay. Passionate about distributed systems and high-throughput APIs.",
    },
    {
        "id": "c002",
        "name": "Priya Nair",
        "current_title": "Software Engineer II",
        "years_experience": 3,
        "skills": ["Python", "Django", "MySQL", "Docker", "AWS EC2", "REST APIs", "Celery"],
        "location": "Bangalore",
        "remote_open": True,
        "compensation_expectation": "16-20 LPA",
        "education": "M.Tech Software Engineering, NIT Trichy",
        "recent_companies": ["Swiggy", "Infosys"],
        "availability": "2 weeks",
        "bio": "Mid-level engineer with strong Django and REST API background. Worked on Swiggy's order management backend. Looking for a growth opportunity with more ownership.",
    },
    {
        "id": "c003",
        "name": "Rohit Sharma",
        "current_title": "Staff Engineer",
        "years_experience": 9,
        "skills": ["Python", "Go", "Kubernetes", "AWS", "PostgreSQL", "Redis", "Kafka", "gRPC", "System Design"],
        "location": "Hyderabad",
        "remote_open": False,
        "compensation_expectation": "45-55 LPA",
        "education": "B.Tech IIT Bombay",
        "recent_companies": ["Google", "Zepto"],
        "availability": "1 month",
        "bio": "Staff-level engineer with experience spanning Google and early-stage startups. Leads distributed systems architecture. Compensation expectation may be above typical range for most roles.",
    },
    {
        "id": "c004",
        "name": "Sneha Kulkarni",
        "current_title": "Backend Developer",
        "years_experience": 4,
        "skills": ["Python", "Flask", "FastAPI", "PostgreSQL", "Redis", "Docker", "AWS RDS", "SQS"],
        "location": "Pune",
        "remote_open": True,
        "compensation_expectation": "20-25 LPA",
        "education": "B.E Computer Engineering, Pune University",
        "recent_companies": ["Cred", "TCS"],
        "availability": "immediate",
        "bio": "Product-minded backend developer with fintech and lending platform experience at Cred. Built microservices for credit score APIs and loan processing workflows. Immediate joiner.",
    },
    {
        "id": "c005",
        "name": "Vikram Rao",
        "current_title": "Senior Software Engineer",
        "years_experience": 7,
        "skills": ["Java", "Spring Boot", "MySQL", "Kafka", "Docker", "AWS", "microservices"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "30-36 LPA",
        "education": "B.Tech JNTU Hyderabad",
        "recent_companies": ["Wipro", "HDFC Bank Tech"],
        "availability": "1 month",
        "bio": "Java-heavy backend engineer with banking domain experience. Strong microservices and Kafka background. Not currently skilled in Python but open to learning.",
    },
    {
        "id": "c006",
        "name": "Divya Krishnamurthy",
        "current_title": "ML Engineer",
        "years_experience": 4,
        "skills": ["Python", "TensorFlow", "Pandas", "FastAPI", "PostgreSQL", "Docker", "GCP"],
        "location": "Bangalore",
        "remote_open": True,
        "compensation_expectation": "24-28 LPA",
        "education": "M.Tech AI/ML, IISc Bangalore",
        "recent_companies": ["PhonePe", "Fractal Analytics"],
        "availability": "2 weeks",
        "bio": "ML engineer transitioning toward backend platform roles. Has Python and FastAPI skills but primary experience is in ML pipelines, not production microservices. Looking to pivot.",
    },
    {
        "id": "c007",
        "name": "Aakash Gupta",
        "current_title": "Principal Engineer",
        "years_experience": 12,
        "skills": ["Python", "Go", "FastAPI", "PostgreSQL", "Redis", "Kafka", "Kubernetes", "AWS", "fintech", "payments"],
        "location": "Mumbai",
        "remote_open": True,
        "compensation_expectation": "60-75 LPA",
        "education": "B.Tech IIT Delhi",
        "recent_companies": ["Paytm", "Goldman Sachs Tech"],
        "availability": "not looking",
        "bio": "Principal engineer with 12 years in fintech payments. Deep expertise in the domain but currently very happy in his role and not actively exploring. Would take only an exceptional opportunity.",
    },
    {
        "id": "c008",
        "name": "Meera Venkatesh",
        "current_title": "Backend Engineer",
        "years_experience": 2,
        "skills": ["Python", "Django", "SQLite", "REST APIs", "Git", "Linux"],
        "location": "Chennai",
        "remote_open": True,
        "compensation_expectation": "10-13 LPA",
        "education": "B.E Information Technology, Anna University",
        "recent_companies": ["Zoho"],
        "availability": "2 weeks",
        "bio": "Junior engineer from Zoho with strong Python fundamentals. Limited exposure to cloud infrastructure and distributed systems. Eager to grow in a product company environment.",
    },
    {
        "id": "c009",
        "name": "Karan Malhotra",
        "current_title": "DevOps Engineer",
        "years_experience": 5,
        "skills": ["Kubernetes", "Docker", "AWS", "Terraform", "CI/CD", "Python scripting", "Redis", "PostgreSQL"],
        "location": "Hyderabad",
        "remote_open": False,
        "compensation_expectation": "26-30 LPA",
        "education": "B.Tech NIT Warangal",
        "recent_companies": ["Amazon", "Ola"],
        "availability": "1 month",
        "bio": "DevOps engineer with strong cloud and infra skills. Has Python scripting and database experience but primary role is infrastructure, not application backend development.",
    },
    {
        "id": "c010",
        "name": "Ananya Iyer",
        "current_title": "Senior Backend Engineer",
        "years_experience": 6,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "AWS ECS", "SQS", "Docker", "microservices", "payments"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "30-35 LPA",
        "education": "B.Tech IIIT Hyderabad",
        "recent_companies": ["BharatPe", "Juspay"],
        "availability": "2 weeks",
        "bio": "Senior engineer specializing in payments infrastructure at Juspay and BharatPe. Has hands-on AWS ECS and SQS experience alongside FastAPI microservices. Strong fintech domain fit.",
    },
    {
        "id": "c011",
        "name": "Suresh Babu",
        "current_title": "Full Stack Developer",
        "years_experience": 4,
        "skills": ["Python", "Django", "React", "PostgreSQL", "Docker", "AWS", "REST APIs"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "18-22 LPA",
        "education": "B.Tech Osmania University",
        "recent_companies": ["Freshworks", "Startup (early stage)"],
        "availability": "immediate",
        "bio": "Full-stack developer leaning more toward backend Python/Django. Built internal tools and B2B SaaS features at Freshworks. Not specialized in high-scale distributed systems.",
    },
    {
        "id": "c012",
        "name": "Nisha Patel",
        "current_title": "Senior Software Engineer",
        "years_experience": 5,
        "skills": ["Python", "FastAPI", "Kafka", "PostgreSQL", "Redis", "Kubernetes", "GCP", "microservices"],
        "location": "Bangalore",
        "remote_open": True,
        "compensation_expectation": "28-33 LPA",
        "education": "B.Tech VIT Vellore",
        "recent_companies": ["Meesho", "Ola Money"],
        "availability": "1 month",
        "bio": "Strong backend engineer with Kafka and microservices expertise from Ola Money's wallet infrastructure. Very good technical match; slightly outside Hyderabad but open to relocation.",
    },
    {
        "id": "c013",
        "name": "Tarun Joshi",
        "current_title": "Associate Software Engineer",
        "years_experience": 1,
        "skills": ["Python", "Flask", "MySQL", "Git", "REST APIs"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "7-9 LPA",
        "education": "B.Tech JNTU 2023",
        "recent_companies": ["Accenture"],
        "availability": "immediate",
        "bio": "Fresher-level engineer with basic Python and Flask skills. Enthusiastic but lacks the seniority and infrastructure experience required for most senior backend roles.",
    },
    {
        "id": "c014",
        "name": "Deepak Reddy",
        "current_title": "Backend Tech Lead",
        "years_experience": 8,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "AWS", "Kafka", "Docker", "Kubernetes", "fintech"],
        "location": "Hyderabad",
        "remote_open": False,
        "compensation_expectation": "38-45 LPA",
        "education": "M.Tech Computer Science, IIIT Hyderabad",
        "recent_companies": ["Slice", "PayU"],
        "availability": "1 month",
        "bio": "Tech lead at Slice managing a team of 6 engineers building lending and credit infrastructure. Excellent technical fit and domain expertise; compensation slightly above mid-range.",
    },
    {
        "id": "c015",
        "name": "Pallavi Singh",
        "current_title": "Software Engineer",
        "years_experience": 3,
        "skills": ["Node.js", "Express", "MongoDB", "Redis", "Docker", "AWS Lambda"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "15-18 LPA",
        "education": "B.Tech Amity University",
        "recent_companies": ["InMobi", "startup"],
        "availability": "immediate",
        "bio": "Node.js focused backend engineer. Has Redis and Docker experience but is not a Python developer and has no SQL or Kubernetes exposure. Poor match for Python-heavy roles.",
    },
    {
        "id": "c016",
        "name": "Rahul Verma",
        "current_title": "Senior Backend Engineer",
        "years_experience": 6,
        "skills": ["Python", "Django", "FastAPI", "PostgreSQL", "Redis", "AWS RDS", "SQS", "ECS", "Docker"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "26-30 LPA",
        "education": "B.Tech NIT Calicut",
        "recent_companies": ["Groww", "Zerodha"],
        "availability": "2 weeks",
        "bio": "Senior engineer from India's leading fintech investment platforms. Experience with both Django and FastAPI, AWS ECS, RDS, and SQS — very strong cloud and backend stack alignment.",
    },
    {
        "id": "c017",
        "name": "Kavitha Rajan",
        "current_title": "Data Engineer",
        "years_experience": 4,
        "skills": ["Python", "Spark", "Airflow", "PostgreSQL", "Redshift", "AWS", "dbt"],
        "location": "Bangalore",
        "remote_open": True,
        "compensation_expectation": "22-26 LPA",
        "education": "B.Tech PSG Tech",
        "recent_companies": ["Swiggy", "Mu Sigma"],
        "availability": "2 weeks",
        "bio": "Data engineer with strong Python and PostgreSQL skills but focused on data pipelines and analytics, not application backend services. Not a microservices engineer.",
    },
    {
        "id": "c018",
        "name": "Siddharth Kumar",
        "current_title": "Senior Software Engineer",
        "years_experience": 5,
        "skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "AWS", "Kubernetes", "payments", "UPI"],
        "location": "Mumbai",
        "remote_open": True,
        "compensation_expectation": "28-34 LPA",
        "education": "B.Tech IIT Kharagpur",
        "recent_companies": ["NPCI", "Pine Labs"],
        "availability": "immediate",
        "bio": "Engineer with deep UPI and payments protocol experience at NPCI and Pine Labs. Strong full backend stack. Mumbai-based but actively prefers remote or Hyderabad relocation.",
    },
    {
        "id": "c019",
        "name": "Amrita Desai",
        "current_title": "Backend Engineer",
        "years_experience": 4,
        "skills": ["Python", "Flask", "PostgreSQL", "Docker", "AWS EC2", "Redis", "Celery"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "19-23 LPA",
        "education": "B.Tech BITS Hyderabad",
        "recent_companies": ["MakeMyTrip", "OYO"],
        "availability": "1 month",
        "bio": "Backend engineer from travel-tech domain. Solid Python and PostgreSQL skills, familiar with Redis and Celery for async workloads. Lacks Kubernetes and fintech domain background.",
    },
    {
        "id": "c020",
        "name": "Nikhil Bhatt",
        "current_title": "Senior Backend Engineer",
        "years_experience": 7,
        "skills": ["Python", "FastAPI", "Go", "PostgreSQL", "Redis", "Kafka", "Kubernetes", "AWS", "fintech", "microservices"],
        "location": "Hyderabad",
        "remote_open": True,
        "compensation_expectation": "32-40 LPA",
        "education": "B.Tech IIIT Allahabad",
        "recent_companies": ["Razorpay", "Cashfree"],
        "availability": "2 weeks",
        "bio": "Highly experienced fintech backend engineer from Razorpay and Cashfree. Covers Python, Go, Kafka, Kubernetes, and AWS — near-perfect stack match for payment platform roles. Reasonable comp expectations.",
    },
]


def get_all_candidates() -> list[dict]:
    """
    Returns all 20 candidate profiles from the mock store.

    Returns:
        list[dict]: Full list of candidate profile dictionaries.
    """
    return CANDIDATE_PROFILES


def get_candidate_by_id(candidate_id: str) -> Optional[dict]:
    """
    Retrieves a single candidate profile by ID.

    Args:
        candidate_id: The unique ID string (e.g. 'c001').

    Returns:
        dict if found, None otherwise.
    """
    for candidate in CANDIDATE_PROFILES:
        if candidate["id"] == candidate_id:
            return candidate
    return None